# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyLibApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'MyLib', :source => 'https://github.com/zacdaryl/Specs.git'
  # Pods for MyLibApp

  target 'MyLibAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyLibAppUITests' do
    # Pods for testing
  end

end
